name: Automated Homebrew update

on:
  schedule:
    - cron: 27 7 * * *
  workflow_dispatch: {}

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  update:
    name: Homebrew update

    runs-on: macos-14
    environment: automated

    steps:
      - uses: macauley/action-homebrew-bump-cask@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tap: freelensapp/tap
          cask: freelens
          livecheck: true
          dryrun: false
